version: '3.7'

services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data/pgdata
  application:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./application:/application
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

volumes:
  data:
