# Generated by Django 4.0.3 on 2022-03-19 13:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_poll_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=55), size=2),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=250),
        ),
    ]
