# Generated by Django 4.0.3 on 2022-03-19 15:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_poll_answers_alter_poll_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.UUIDField(default=uuid.UUID('24555b3a-5695-4d54-bd68-f574433a58ce'), editable=False, primary_key=True, serialize=False),
        ),
    ]
