# Generated by Django 4.0.3 on 2022-03-19 15:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_poll_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='id',
        ),
        migrations.AddField(
            model_name='poll',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f3fa4b79-8afd-4114-a42b-e1b1c2d664ea'), editable=False, primary_key=True, serialize=False),
        ),
    ]
